# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0261b2748965d77df1c13def483892fc784f7222717a08cadc51668a94f80b097d21d061fe685f1bed3e15816776e58fef9affa57108ff16f8c37cc435ea54f1

test:
  secret_key_base: 1e0e17c03ecbbe245a3ecc01c323955e44a0c30231f3299be8336ec9ca7b71ef531d3a129ed43fe26950ca465f1b7d57be226e72f72e992c725b94cc4d212040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
